// AUTO-GENERATED FILE - DO NOT MODIFY
// Generated from lib/error.babel
// Babel's Error Format

package com.concur.babel;

import com.google.gson.annotations.SerializedName;
import java.io.Serializable;




/**
 * ServiceError defines the error response generated by Babel for service failures
 */
public class ServiceError implements Serializable {	



	/**
	 * Time of the error
	 */
	@SerializedName("Time")
	private java.util.Date time;


	/**
	 * Tags to categorize the error
	 */
	@SerializedName("Tags")
	private java.util.List<String> tags = new java.util.ArrayList<String>();


	/**
	 * A list of errors that occurred
	 */
	@SerializedName("Errors")
	private java.util.List<Error> errors = new java.util.ArrayList<Error>();


	/**
	 * Context is a map of additional error details and context
	 */
	@SerializedName("Context")
	private java.util.Map<String,java.util.Map<String,String>> context = new java.util.HashMap<String,java.util.Map<String,String>>();


	/**
	 * Details contains optional detailed error information, such as error messages
	 * or a stack trace specific to the given server environment
	 */
	@SerializedName("Details")
	private String details;


	/**
	 * Inner points to a service error propagated from another tier that is using Babel
	 */
	@SerializedName("Inner")
	private ServiceError inner;

	public ServiceError() {}

	public ServiceError(
		java.util.Date time,
		java.util.List<String> tags,
		java.util.List<Error> errors,
		java.util.Map<String,java.util.Map<String,String>> context,
		String details,
		ServiceError inner)
	{

		this.time = time;
		this.tags = tags;
		this.errors = errors;
		this.context = context;
		this.details = details;
		this.inner = inner;
	}

	public java.util.Date getTime() { return this.time; };
	public void setTime(java.util.Date time) {
		this.time = time;
	}

	public java.util.List<String> getTags() { return this.tags; };
	public void setTags(java.util.List<String> tags) {
		this.tags = tags;
	}

	public java.util.List<Error> getErrors() { return this.errors; };
	public void setErrors(java.util.List<Error> errors) {
		this.errors = errors;
	}

	public java.util.Map<String,java.util.Map<String,String>> getContext() { return this.context; };
	public void setContext(java.util.Map<String,java.util.Map<String,String>> context) {
		this.context = context;
	}

	public String getDetails() { return this.details; };
	public void setDetails(String details) {
		this.details = details;
	}

	public ServiceError getInner() { return this.inner; };
	public void setInner(ServiceError inner) {
		this.inner = inner;
	}
	
	public String toString() {
		StringBuilder sb = new StringBuilder("ServiceError(");
		sb.append("time:");
		sb.append(this.time + ", ");
		sb.append("tags:");
		sb.append(this.tags + ", ");
		sb.append("errors:");
		sb.append(this.errors + ", ");
		sb.append("context:");
		sb.append(this.context + ", ");
		sb.append("details:");
		sb.append(this.details + ", ");
		sb.append("inner:");
		sb.append(this.inner + ")");
		return sb.toString();
	}
}